# Generated by Django 6.0.6 on 2026-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyLogin",
            fields=[
                (
                    "id",
                    models.TextField(
                        db_column="ID",
                        default="admin",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.TextField(db_column="Password", default="admin")),
            ],
            options={
                "db_table": "companylogintable",
            },
        ),
        migrations.CreateModel(
            name="ContactTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.TextField(db_column="Fullname")),
                ("city", models.TextField(db_column="City")),
                ("contact", models.TextField(db_column="Contact")),
                ("query", models.TextField(db_column="Query")),
            ],
            options={
                "db_table": "contacttable",
            },
        ),
        migrations.CreateModel(
            name="CustomerComplaint",
            fields=[
                (
                    "complainid",
                    models.AutoField(
                        db_column="complainid", primary_key=True, serialize=False
                    ),
                ),
                ("customerid", models.TextField(db_column="customerid")),
                (
                    "orderid",
                    models.IntegerField(blank=True, db_column="orderid", null=True),
                ),
                ("complain", models.TextField(db_column="complain")),
                ("dateofcomplain", models.TextField(db_column="dateofcomplain")),
                ("complainstatus", models.TextField(db_column="complainstatus")),
            ],
            options={
                "db_table": "customercomplaintable",
            },
        ),
        migrations.CreateModel(
            name="CustomerOrderFuel",
            fields=[
                (
                    "orderid",
                    models.AutoField(
                        db_column="Orderid", primary_key=True, serialize=False
                    ),
                ),
                ("customer_id", models.TextField(db_column="ID")),
                ("fuelcategory", models.TextField(db_column="Fuelcategory")),
                ("fueltype", models.TextField(db_column="fueltype")),
                ("quantity", models.TextField(db_column="quantity")),
                ("droplocation", models.TextField(db_column="droplocation")),
                ("contact", models.TextField(db_column="contact")),
            ],
            options={
                "db_table": "customerorderfueltable",
            },
        ),
        migrations.CreateModel(
            name="CustomerSignup",
            fields=[
                (
                    "id",
                    models.TextField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("password", models.TextField(db_column="Password")),
                ("fullname", models.TextField(db_column="Fullname")),
                ("address", models.TextField(db_column="Address")),
                ("city", models.TextField(db_column="City")),
                ("contact", models.TextField(db_column="Contact")),
                ("gender", models.TextField(db_column="Gender")),
                ("dob", models.TextField(db_column="DOB")),
                ("emailid", models.TextField(db_column="EmailId")),
            ],
            options={
                "db_table": "customersignup",
            },
        ),
        migrations.CreateModel(
            name="FeedbackTable",
            fields=[
                (
                    "customerid",
                    models.TextField(
                        db_column="CustomerId", primary_key=True, serialize=False
                    ),
                ),
                ("feedback", models.TextField(db_column="Feedback")),
            ],
            options={
                "db_table": "feedbacktable",
            },
        ),
        migrations.CreateModel(
            name="OrderEvCharging",
            fields=[
                (
                    "orderid",
                    models.AutoField(
                        db_column="orderid", primary_key=True, serialize=False
                    ),
                ),
                ("customerid", models.TextField(db_column="customerid")),
                ("droplocation", models.TextField(db_column="droplocation")),
                ("contact", models.TextField(db_column="contact")),
            ],
            options={
                "db_table": "orderevchargingtable",
            },
        ),
    ]
